basePath: /
definitions:
  contracts.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  contracts.PagedResponse-contracts_UserResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/contracts.UserResponse'
        type: array
      pagination:
        $ref: '#/definitions/contracts.Pagination'
    type: object
  contracts.Pagination:
    properties:
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
  contracts.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A basic user management API
  title: User API
  version: "1.0"
paths:
  /users:
    get:
      description: Returns a paged list of users
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contracts.PagedResponse-contracts_UserResponse'
        "500":
          description: internal error
          schema:
            type: string
      summary: Get paged users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Creates a new user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/contracts.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/contracts.UserResponse'
        "400":
          description: invalid request body
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: Create user
      tags:
      - Users
  /users/{id}:
    get:
      description: Returns a single user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contracts.UserResponse'
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Get user by ID
      tags:
      - Users
swagger: "2.0"
tags:
- description: Operations for managing users
  name: Users
